### ISSUE TITLE
Testing needed

### ISSUE THREAD

**Issue by michaeldeboeve** [michaeldeboeve/generator-robonkey#3]
I've written the generator from the ground up, but it needs more testing before I can push it to npm.
Anybody willing to help can pull the developer branch. My everlasting gratitude will be yours.

**Comment by damianoferrari** [comment]
Hi @michaeldeboeve, I tested the new generator on my work PC (Windows 7), and I am not having much luck. 

I can generate a project just fine, but the browser will get stuck while trying to load localhost:3000. For what it's worth, Browsersync is running and I can access localhost:3001. 

I don't see any obvious errors, just a blank page that never fully loads. I also noticed that any file changes (e.g., to index.html) aren't detected until I stop gulp serve and start it again.

**Comment by michaeldeboeve** [comment]
Thanks @damianoferrari! Did you do a recent pull? Because I fixed some browser-sync issues yesterday. Seems like I'll need to test on windows too ^^

**Comment by damianoferrari** [comment]
Just to verify, I checked the code out once again and modified intro.js - I am actually using the latest code. The problem is still the same, however - localhost:3001 loads, localhost:3000 doesn't. I will try later on my Mac and see if it works :)

**Comment by michaeldeboeve** [comment]
can you provide me your generated config.json and browser-sync.js files?

**Comment by michaeldeboeve** [comment]
@damianoferrari, Apparently it's not a windows only issue. I got browser-sync set up to work well with mamp. I'll push a fix, as soon as I fix other bugs.

**Comment by damianoferrari** [comment]
@michaeldeboeve, do you still need the config.json and browser-sync.js files?

**Comment by michaeldeboeve** [comment]
@damianoferrari, nope

**Comment by michaeldeboeve** [comment]
@damianoferrari, I pushed an update.

**Comment by damianoferrari** [comment]
Thanks @michaeldeboeve, it is working now.
